#!/usr/bin/python3
'''
    Purpose: Generate DocsPages for new entries
             rickym270.github.io/#docs
    Notes: Pages are all obtained from ../html/pages/FAQPages
            Those pages are generated by running bin/GenNotes.py

'''
import jinja2
import cgi
import cgitb
import os
from datetime import datetime

cgitb.enable()

TEMPLATE_PATH = "../templates/"
FAQPAGES_PATH = "../html/pages/FAQPages/"
TEMPLATE = "docs.html"

debug_list = []
entries = []
templates = jinja2.Environment(loader=jinja2.FileSystemLoader(searchpath=TEMPLATE_PATH))
print("Content-Type: text/html\r\n\r\n")

for filename in os.listdir(FAQPAGES_PATH):
    name = filename.split('.')[0].replace('_', ' ')
    path = "{}{}".format(FAQPAGES_PATH,filename)

    entries.append((name, path))

template = templates.get_template(TEMPLATE)
with open("../html/pages/docs.html", "w") as f:
    f.write(template.render(entries=entries))

print(template.render(entries=entries))
print("Done.\n\n\n")
